apiVersion: apps/v1
kind: Deployment
metadata:
  name: petelka-api
  labels:
    app: petelka-api
  annotations:
    description: "Развёртывание API интернет магазина Petelka"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petelka-api
  template:
    metadata:
      labels:
        app: petelka-api
    spec:
      containers:
        - name: petelka-api
          image: petelka-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"