apiVersion: v1
kind: Service
metadata:
  name: petelka-api
  annotations:
    description: "Сервис для API интернет магазина Petelka"
spec:
  type: NodePort
  selector:
    app: petelka-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30179